import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createAdminUser, getAdminOptions, getAdminSummary, getAdminUsers, updateAdminCostCentre, updateAdminRole, type AdminOptions, type AdminSummary, type AdminUser } from "../../services/api";
import { formatMoney } from "../../utils/formatters";

export function AdminPortal({ onIdentityChanged }: { onIdentityChanged: () => Promise<void> }) {
  const [summary, setSummary] = useState<AdminSummary | null>(null); const [options, setOptions] = useState<AdminOptions>({ roles: [], cost_centres: [] });
  const [users, setUsers] = useState<AdminUser[]>([]); const [search, setSearch] = useState(""); const [filterRole, setFilterRole] = useState(""); const [filterCentre, setFilterCentre] = useState("");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", password: "", role: "Employee", cost_centre: "" });
  const loadUsers = useCallback(async () => setUsers(await getAdminUsers({ search, role: filterRole, cost_centre: filterCentre })), [search, filterRole, filterCentre]);
  const reload = useCallback(async () => { const [s, o] = await Promise.all([getAdminSummary(), getAdminOptions()]); setSummary(s); setOptions(o); await loadUsers(); }, [loadUsers]);
  useEffect(() => { void reload().catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load the admin portal.")); }, [reload]);
  useEffect(() => { if (!form.cost_centre && options.cost_centres[0]) setForm((current) => ({ ...current, cost_centre: options.cost_centres[0] })); }, [options.cost_centres, form.cost_centre]);
  async function action(operation: () => Promise<unknown>, message: string) { setBusy(true); setError(""); setNotice(""); try { await operation(); await reload(); await onIdentityChanged(); setNotice(message); } catch (cause) { setError(cause instanceof Error ? cause.message : "The change could not be saved."); } finally { setBusy(false); } }
  async function addUser(event: FormEvent) { event.preventDefault(); await action(() => createAdminUser(form), "The account was created in the database."); setForm((current) => ({ ...current, name: "", email: "", password: "" })); }
  return <main className="dashboard admin-page"><div className="welcome"><div><p className="section-kicker">Access governed by backend RBAC</p><h1>Admin Portal</h1><p>Manage database-backed accounts, roles, and cost-centre assignments.</p></div><span className="workspace-status">Admin actions are audited</span></div>
    {error && <p role="alert" className="login-error">{error}</p>}{notice && <p role="status" className="expense-success">{notice}</p>}
    {summary && <div className="real-summary-grid admin-summary-grid"><article className="panel real-summary"><small>Database users</small><strong>{summary.user_count}</strong><span>{summary.users_by_role.map((row) => `${row.role}: ${row.count}`).join(" · ")}</span></article><article className="panel real-summary"><small>Expenses</small><strong>{summary.expense_count}</strong><span>All stored expense records</span></article>{summary.spend_by_currency.map((row) => <article className="panel real-summary" key={row.currency}><small>Organization spend · {row.currency}</small><strong>{formatMoney(row.amount, row.currency)}</strong><span>Totals are kept separate by currency</span></article>)}</div>}
    <section className="panel admin-create"><div className="panel-heading"><div><p className="section-kicker">Create account</p><h2>Provision a user</h2></div></div><form className="admin-user-form" onSubmit={(event) => void addUser(event)}>
      <label className="field"><span>Name</span><input required maxLength={100} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label>
      <label className="field"><span>Email</span><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label>
      <label className="field"><span>Initial password (12+ characters)</span><input required minLength={12} maxLength={72} type="password" autoComplete="new-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label>
      <label className="field"><span>Role</span><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}>{options.roles.map((role) => <option key={role}>{role}</option>)}</select></label>
      <label className="field"><span>Cost centre</span><select required value={form.cost_centre} onChange={(event) => setForm({ ...form, cost_centre: event.target.value })}>{options.cost_centres.map((centre) => <option key={centre}>{centre}</option>)}</select></label>
      <button className="primary" disabled={busy || !options.cost_centres.length}>{busy ? "Saving…" : "Create user"}</button>
    </form></section>
    <section className="panel admin-directory"><div className="panel-heading"><div><p className="section-kicker">User directory</p><h2>Manage access</h2></div><span>{users.length} matching accounts</span></div>
      <div className="admin-filters"><label className="field"><span>Search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, email or ID" /></label><label className="field"><span>Role</span><select value={filterRole} onChange={(event) => setFilterRole(event.target.value)}><option value="">All roles</option>{options.roles.map((role) => <option key={role}>{role}</option>)}</select></label><label className="field"><span>Cost centre</span><select value={filterCentre} onChange={(event) => setFilterCentre(event.target.value)}><option value="">All cost centres</option>{options.cost_centres.map((centre) => <option key={centre}>{centre}</option>)}</select></label></div>
      <div className="table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Cost centre</th></tr></thead><tbody>{users.map((user) => <tr key={user.user_id}><td><strong>{user.name}</strong><small>{user.user_id}</small></td><td>{user.email}</td><td><select aria-label={`Role for ${user.email}`} value={user.role} disabled={busy} onChange={(event) => void action(() => updateAdminRole(user.user_id, event.target.value), `Role updated for ${user.email}.`)}>{options.roles.map((role) => <option key={role}>{role}</option>)}</select></td><td><select aria-label={`Cost centre for ${user.email}`} value={user.cost_centre} disabled={busy} onChange={(event) => void action(() => updateAdminCostCentre(user.user_id, event.target.value), `Cost centre updated for ${user.email}.`)}>{options.cost_centres.map((centre) => <option key={centre}>{centre}</option>)}</select></td></tr>)}</tbody></table>{users.length === 0 && <p className="analytics-empty">No users match these filters.</p>}</div>
    </section>
  </main>;
}
